### ISSUE TITLE
Some art

### ISSUE THREAD

**Issue by Tahayid** [Tahayid/hidesensitive#5]
Definitely need some art, like an icon and stuff.

Anyone willing to help would be much appreciated :D

**Comment by Yoyomortal09** [comment]
At first hide sensitive used to for my iPhone 6 plus after i update it it don't work no more I wonder

**Comment by d4rkh0rse** [comment]
I'm not sure what that has to do with art, but open an issue with more information.

**Comment by Yoyomortal09** [comment]
I like this tweak but after I update yesterday it don't woek no more I uninstalled and re install it but it doesn't work no more

**Comment by Yoyomortal09** [comment]
Thanks I just receive the update hide sensitive works fine now thanks

**Comment by Tahayid** [comment]
HideSensitive is no longer maintained. All issues are being closed.
